CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "Quote" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "text" TEXT NOT NULL,
  "fingerprint" TEXT NOT NULL UNIQUE,
  "elo" INTEGER NOT NULL DEFAULT 1200,
  "wins" INTEGER NOT NULL DEFAULT 0,
  "losses" INTEGER NOT NULL DEFAULT 0,
  "voteCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
